export enum ENV_VARIABLE {
    APP_PORT = 'APP_PORT',
    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_USERNAME = 'DB_USERNAME',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_NAME = 'DB_NAME',
    DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
}
export const REQUIRED_ENV_VARIABLES = [
    ENV_VARIABLE.APP_PORT,
    ENV_VARIABLE.DB_HOST,
    ENV_VARIABLE.DB_PORT,
    ENV_VARIABLE.DB_USERNAME,
    ENV_VARIABLE.DB_PASSWORD,
    ENV_VARIABLE.DB_NAME,
];
